### ISSUE TITLE
bfa like "remember know gear" to be used on xmorg

### ISSUE THREAD

**Issue by Aokromes** [Rochet2/TrinityCore#121]
I was asked multiple times this by female friends since they use to use all bank inventory on clothes.

352944266822 N/R

**Comment by Rochet2** [comment]
`transmog_legion_3.3.5` branch now finally has a somewhat working version.
Started on it 2 years ago at least, but finally found the time and energy to make it working.
You may want to take a look at the changelog.

https://github.com/Rochet2/TrinityCore/blob/transmog_legion_3.3.5/src/server/scripts/Custom/Transmog/CHANGELOG.md
https://github.com/Rochet2/TrinityCore/compare/TrinityCore:3.3.5...transmog_legion_3.3.5.diff

This is a somewhat beta release as its not really tested much in the wild.

**Comment by qyh214** [comment]
seems cool.Very excited and can't wait to test.
but there are some technical problems:
I have used transmog_335 and transmog_vendor_335 ,can I upgrade to transmog_legion_3.3.5 from transmog_335 branch?
and Do I want to remove transmog_vendor_335 branch or also compatible?

**Comment by Aokromes** [comment]
/home/runner/work/TrinityCore/TrinityCore/src/server/game/Entities/Item/Transmogrification.cpp: In member function ‘std::__cxx11::string Transmogrification::GetItemName(const Item*, WorldSession*)’:
/home/runner/work/TrinityCore/TrinityCore/src/server/game/Entities/Item/Transmogrification.cpp:202:39: error: comparison is always true due to limited range of data type [-Werror=type-limits]
             name += (*suffix)[loc_idx >= 0 ? loc_idx : DEFAULT_LOCALE];
                               ~~~~~~~~^~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1453: src/server/game/CMakeFiles/game.dir/Entities/Item/Transmogrification.cpp.o] Error 1

**Comment by Rochet2** [comment]
> can I upgrade to transmog_legion_3.3.5 from transmog_335 branch

- I have not tried.
- But as it is now, the branches can be merged together with git merge (or cherry pick the commit(s)?) as the new version was built on top of old one. So code can be updated relatively easily.
- And when it comes to DB, the update SQL should add new columns and tables and reuse the transmog column that already existed. So old transmogs will work with new system.
- Old sets may not work as a new column was added to the set data to signal either enchant or transmog. The set data needs some kind of transformation script. So you may want to rename the old set DB and then migrate the data to the new one.

> remove transmog_vendor_335 branch or also compatible

I do not know about that. I would guess that since the systems are quite different, there are at least some compatibility issues.
The vendor code would need to only work as a store-front and otherwise apply the transmogs using the new system.

**Comment by Rochet2** [comment]
@Aokromes The CI errors are now fixed

**Comment by Rochet2** [comment]
crash fix https://github.com/Rochet2/TrinityCore/commit/bbfd8254efab33da90d48b5d29c05e2c974d22ff

**Comment by Aokromes** [comment]
it looks to fail to store items if

Transmogrification.AllowMixedArmorTypes = 1
Transmogrification.AllowMixedWeaponTypes = 1

enabled.

**Comment by Rochet2** [comment]
AllowMixed should now be fixed with https://github.com/Rochet2/TrinityCore/commit/7e3256a56816846d9310140676ef8180e7186610
Also fixed remove pending enchant/transmog removing both https://github.com/Rochet2/TrinityCore/commit/ffcb843ae7dd873a8c95e0c3ff5119e65e2e2597

**Comment by Rochet2** [comment]
There is now a setting to control soulbound item requirement a bit better. I also made it so that items are checked when they are moved around even if they are not bound.

**Comment by Rochet2** [comment]
Startup crash fix related to guild bank item loading: https://github.com/Rochet2/TrinityCore/commit/da87591868a938a1974d5584937e708857bc283b

**Comment by Aokromes** [comment]
i think this ticket can be closed already, working good.

**Comment by Rochet2** [comment]
Crash fix https://github.com/Rochet2/TrinityCore/commit/28f9f641bb430d6199280386069c9953690a3397
