### ISSUE TITLE
3.3.5-transmogrify branch not updated since December 2020

### ISSUE THREAD

**Issue by jackpoz** [Rochet2/TrinityCore#129]
https://github.com/Rochet2/TrinityCore/commits/transmog_3.3.5 shows that the last update was on december 2020:
![image](https://user-images.githubusercontent.com/1153754/105844322-5abfe700-5fd9-11eb-83b7-941b692f347e.png)

Maybe there's a merge conflict to be fixed

**Comment by Rochet2** [comment]
There probably was a conflict. Also, the CI was actually was blocked from pushing new versions for some reason.
The current situation of all branches can be seen here: https://github.com/Rochet2/TrinityCore3.3.5/actions/runs/528443174
Some are still broken probably due to the recent gossip and command changes in TC that require manual work to get working.

Closing this as the CI can now push updates and the conflict (if any) was fixed on the transmog_3.3.5 branch with the PR that was merged.
Thanks.

**Comment by jackpoz** [comment]
did you switch from travis to GitHub Actions to update the branches ? any feedback about that ?

**Comment by Rochet2** [comment]
Yeah I did witch. Here are some notes.
pro:
- integration is nice, UX is nice. They seem to have improved it over time a bit. It used to be difficult to find the PR related to a build for example, but now the summary page has a link.
- actions are nice as you can just take something that already exists and does some difficult to do things for you
- speed and parallelism are better compared to Travis.
- way higher time limit than on Travis, so no need for workarounds related to that
- multiple CI configurations in separate files
- Mac, Linux, and Windows support
- think there is some kind of private repo support also? think I used that for a few projects
- more than just CI with the github interaction to handle labeling etc.
- The build log looks nicer than on travis as travis just had a bunch of shell scripts while here we can have a verbose file with conditionals and named steps.
- Artifacts can be uploaded (map generators?)

con:
- when I began using actions some of the things were not working properly as it was just released (might be fixed? For example, some env variables and libraries were faulty or incomplete (not dev versions, light versions, etc)
- The logs are not stored for a long time, at least by default. I think the default is 90 days and your CI log is gone. A few times I have gone back to look something up and it just doesn't exist anymore.
- With increased parallelism and builds etc the cache is great, but it's a bit small for some uses. especially when several builds are done. I'm not sure if there could be some solutions for this.

I don't think it's missing anything crucial that Travis has and rather adds onto it. It doesn't have as extensive functionality as circle-ci I believe, but I could be wrong as I have not read the docs too thoroughly for some time now.
It seems that GH actions stop running the scheduled run if the repo isn't pushed regularly.

I guess it was a bit weird when you added a github action to TC to build the core and then my CI started running that when I pulled the latest core for some fork. The build failed due to custom code that I then later fixed to fix the constant errors the CI you devilishly 😈 forced onto me generated .. ooh this horror ..  😨

I have been moving many things to github actions over the year now that it has been available. I prefer to use it over travis, mainly because of the parallelism limitation of Travis.

You maybe interested in the look and set up of these runs and their workflow files:
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/529174032
https://github.com/Rochet2/TrinityCore3.3.5/actions/runs/529342698
https://github.com/azerothcore/azerothcore-wotlk/actions
I think they demonstrate nicely the use of actions in various ways.

**Comment by jackpoz** [comment]
well I have written a few actions in typescript for TC, pushing them to https://github.com/TrinityCore/GitHub-Actions/branches/all . Travis was the first CI but now it doesn't seem to have kept up with every other available CI, being slow and updated not so often. I guess one day I will have to move the automerger cron to circle-ci or GH actions.
