### ISSUE TITLE
About tabard and shirt in transmog

### ISSUE THREAD

**Issue by verven36** [Rochet2/TrinityCore#134]
hi,
first of all , thanks to your amazing transmog system
 
could you check to as below issue 

1. I cant' transmog tabard and shirt , even though vendor has section about it 
    plz let me know If you have any solution about it 

2. Can I use to hidden tabard and shirt in your transmog system ?
   as you know, that Item updated 7.3.5 ( we've used 3.3.5 ) - I think that's impossible 
   https://www.wowhead.com/item=142504/hidden-tabard?bonus=0
   
   If we can't use it , can we make an Items of hidden tabard & shirt in trinitycore 3.3.5

**Comment by Rochet2** [comment]
1. Set
Transmogrification.IgnoreReqStats = 1
Transmogrification.AllowCommon = 1
to allow transmogrification of tabard item entry 5976 to 11364.
Same thing for shirts, for example item entry 38 and 45 work fine after those config settings are edited.
Read through the settings in the config carefully and try see if they could be changed if you have similar problems.

2. You should be able to. Try making items that have displayID set to 0. Alternatively you could try browse through the item displayids and try find an item display that is invisible - there might be some. You may want to set `DBC.EnforceItemAttributes = 0` in worldserver config if you are trying to edit the displayid of an existing item in DB as DB data is ignored otherwise.

**Comment by Rochet2** [comment]
I assume issues were resolved, closing.
