### ISSUE TITLE
Player and item gossip doesn't work

### ISSUE THREAD

**Issue by qyh214** [Rochet2/TrinityCore#54]
**Description**:Player and item gossip doesn't work

**Current behaviour**: doesn't work.no gossip show

**Expected behaviour**:  work.show gossip

**Steps to reproduce the problem**:

1. use exmple code and build
2. in game
3. levelup 1(no goosip show)
4.add a item with scriptname=example_ItemGossip
5.in game add .add this item id and nothing(no goosip show)

**Branch(es)**: 335

**TC hash/commit**:  xx

**TDB version**:  xx

**Operating system**:  win 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rochet2** [comment]
I dont have time to test this for a few days.
Can you test if it works by applying the scriptname (example_ItemGossip) to hearthstone?
Clear cache and restart server and see ingame if it works with hearthstone. If it does, then the patch works and your item needs to have  a spell on use or something.

Otherwise it is probably the patch at fault or your installation of it.

**Comment by qyh214** [comment]
sorry!!
I made a stupid mistake!!
I forgot add to custom script loader so don't work.......
sad
