### ISSUE TITLE
[DressNPC335] some skins aren't available 

### ISSUE THREAD

**Issue by Hyakkimaru** [Rochet2/TrinityCore#63]
**Description**: We cant create a Blackrock Orc for example, the skinID is 9 (it must be black) but the Orc appears with a green skin. It's like every skin that players can't use aren't available with DressNPC

**Expected behaviour**: It could be good if we could create NPCs with every skin referenced in dbcs.

**Steps to reproduce the problem**:

1. Create an outfit with race 2 and skincolor 9.

**Branch(es)**: 335

Thank you for this patch, it really help us.

**Comment by Rochet2** [comment]
Dressnpcs isnt limiting anything at the moment, so its probably a client limitation.

Some races allow more skins if you choose the correct class. For example choosing class 6 (death knight) will probably allow you to use skins 9,10,11. But since the class is selected as death knight the NPC has DK eyes and the skin color may vary some.

I dont know if there exists some combination that allows using the skin you want without DK eyes etc.
Seems the closest to the one you want is race 2, class 6, skin 11.
