### ISSUE TITLE
Multi Vendor problem

### ISSUE THREAD

**Issue by infusionwowgit** [Rochet2/TrinityCore#67]
**Description**: Hey guys my problem is i wanna use the newest TrinityCore with Lua Engine and the Multivendor script, but if i wanna compile the things i get a error on 92% 

[ 92%] Linking CXX static library libscripts.a
[ 92%] Built target scripts
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Can anyone tell me what for a LIB Error this is? 

**Current behaviour**: Tell us what happens
If i compile the core without the script of rochet2 (multivendor) only the newest TC and newest Lua Engine i get no error... only with the Multivendor merge... i clone first the TC then the LUA Engine at the last point the multivendor like the guide from rochet... its a Rootserver with Linux Debian 9.0 can anyone help me ? or any guide for me?

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. http://www.ac-web.org/forums/showthread.php?208537-Compile-TrinityCore-Merge-Eluna-Lua-Engine-amp-Update-Source-Engine
2. https://github.com/Rochet2/TrinityCore/tree/multivendor/src/server/scripts/Custom/Multivendor
3.  Compile = Error 

**Branch(es)**: 335/6x  
3.3.5a
**TC hash/commit**:  
Newest (Today) 27.01.2018 
**TDB version**:  
TDB 335.63

**Operating system**:  
Linux Debian 9.0

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rochet2** [comment]
Please post full compile log.

**Comment by Rochet2** [comment]
How did you install multivendor? Did you apply it as a diff?

**Comment by infusionwowgit** [comment]
https://pastebin.com/Aapg7Gq3

No i use the direct merge... i test it with the diff way but i got the same error

**Comment by Rochet2** [comment]
In that case you are merging Eluna with TC. The error is caused by the version difference caused by the merge and not by Eluna or multivendor. Please read this regarding merging eluna: https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/MERGING.md

The guide to install Eluna you linked is not an official guide and the official guide does things a bit differently. The installation in that guide also falls under "merging with TC" instead of regular Eluna installation.

Either you fix the errors on your own, wait for it all to work together at some point or install Eluna using the official installation guide and then install patches using diffs. You can find the installation instructions for Eluna here: https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/INSTALL.md

**Comment by infusionwowgit** [comment]
Okay thank you i test it.

**Comment by infusionwowgit** [comment]
Okay i think the Lua Engine is not up to date i test it like your links and i get this error again now i compiled the core without lua and your stuff only the TC and i got no error^^

**Comment by Rochet2** [comment]
> i think the Lua Engine is not up to date

That is right. But that is not an issue in itself.
The issue is using latest and greatest and expecting everything to be compatible with it.

Lets say Eluna is updated once every day to match TC. Is Eluna then "up to date"?
According to what you are saying it is not most of the time, since TC can make any number of commits in a day and whenever they make a single commit Eluna is not "up to date". This can be noticed especially when TC introduces any change that changes something Eluna uses - which has happened multiple times over the past weeks. Additionally whenever something is actually broken in such a way, a developer has to manually fix it which is not doable every day.

**Comment by infusionwowgit** [comment]
Update: Now the TC and your script works perfectly eluna is currently not working i wait on a update..
