### ISSUE TITLE
Transmogrification 

### ISSUE THREAD

**Issue by KaraLegal** [Rochet2/TrinityCore#7]
Good one and my first issue and as you can see I'm using the google translator, but my problem and the following every time I try to compile the TrinityCore appears as follows:

/home/trinity/TrinityCore/src/server/scripts/Custom/Transmog/Transmogrification.cpp: In member function 'void Transmogrification::LoadPlayerSets(Player*)':
/home/trinity/TrinityCore/src/server/scripts/Custom/Transmog/Transmogrification.cpp:65:17: error: 'class Player' has no member named 'presetMap'
player->presetMap[PresetID].name = SetName;

I am using

Ubuntu 4.14 Server 32-bit

TrinityCore revision: 16b42a4 + 2015-09-16 08:14:15 +0200 (3.3.5 branch)
TrinityCore buildtype: Release

**Comment by Rochet2** [comment]
Sounds like for some reason the Transmogrification.h was not included to Player.h
or you have not installed transmogrification correctly and left some important parts out of Player.h.
Check that presetMap exists in Player.h

**Comment by darkmihai** [comment]
[ 36%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Custom/custom_script_loader.cpp.o
[ 36%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Custom/Transmog/Transmogrification.cpp.o
/root/TrinityCore/src/server/scripts/Custom/Transmog/Transmogrification.cpp: In member function ‘void Transmogrification::LoadPlayerSets(Player*)’:
/root/TrinityCore/src/server/scripts/Custom/Transmog/Transmogrification.cpp:52:13: error: ‘class Player’ has no member named ‘presetMap’
     player->presetMap.clear();
             ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Custom/Transmog/Transmogrification.cpp.o] Error 1
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [all] Error 2

**Comment by Rochet2** [comment]
@darkmihai  do as instructed in the previous post:

> Sounds like for some reason the Transmogrification.h was not included to Player.h
> or you have not installed transmogrification correctly and left some important parts out of Player.h.
> Check that presetMap exists in Player.h

**Comment by Rochet2** [comment]
Cannot reproduce
