### ISSUE TITLE
how to use multitrainer?

### ISSUE THREAD

**Issue by qxpf666** [Rochet2/TrinityCore#87]
how to use multitrainer?

**Comment by Rochet2** [comment]
The readme says

> In C++ you can pass the trainer entry to SendTrainerList function. For SQL in world database you can set the trainer entry to the gossip_menu_option table ActionMenuID column for an option that has OptionType 5. The NPC must be a working vendor, so it needs vendor npc flag.

Do you have some problem with it?

**Comment by qxpf666** [comment]
It can not work
can you give some Example like:
MultivendorExample.sql
MultivendorExample.cpp

**Comment by Rochet2** [comment]
I have now changed the code a bit and created working examples for the SQL and C++.
You can see the examples and the new readme here: https://github.com/Rochet2/TrinityCore/tree/multitrainer/src/server/scripts/Custom/multitrainer
Since I changed the code a bit you should probably try update to latest version (git pull or git apply -R multitrainer.diff and apply new code).

**Comment by qxpf666** [comment]
Big thanks
